trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseNode@1
  inputs:
    versionSpec: '14'
    addToPath: true

- script: |
    npm install
    npm test
    npm run build
  displayName: 'Install dependencies, run tests, and build'

- task: Docker@2
  inputs:
    containerRegistry: 'For-Docker' # replace with your Azure Container Registry name
    repository: 'MyNodeAppImage'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
