trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseNode@1
  inputs:
    versionSpec: '14'
    addToPath: true

- script: |
    npm install
    npm test
    npm run build
  displayName: 'Install dependencies, run tests, and build'

- task: Docker@2
  inputs:
    containerRegistry: 'For-Docker' # Use the service connection name
    repository: 'priya1414/mynodeapp-image' # Update to your Docker Hub repository
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest # You can use a specific tag if needed, e.g., $(Build.BuildId)
      # Add these steps to your existing pipeline YAML

- script: |
    docker pull priya1414/mynodeapp-image:latest
    docker run -d -p 3000:3000 priya1414/mynodeapp-image:latest
  displayName: 'Deploy Docker Image'

# Add these steps to your existing pipeline YAML

- script: |
    docker stop my-nodejs-app-container || true # Stop the existing container if it's running
    docker rm my-nodejs-app-container || true   # Remove the existing container if it exists
    docker pull priya1414/mynodeapp-image:latest
    docker run -d -p 3000:3000 --name my-nodejs-app-container priya1414/mynodeapp-image:latest
  displayName: 'Deploy Docker Image'
