trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseNode@1
  inputs:
    versionSpec: '14.17.6'
    addToPath: true

- script: |
    npm install
    npm test
    npm run build
  displayName: 'Install dependencies, run tests, and build'

- task: Docker@2
  inputs:
    containerRegistry: 'For-Docker' # Use the service connection name
    repository: 'priya1414/mynodeapp-image' # Update to your Docker Hub repository
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildId)'
